### ISSUE TITLE
In game you cannot open the store tab or media tab

### ISSUE THREAD

**Issue by Soulphraser** [rasitayaz/decky-brightness-bar#5]
I tried this out with two games, Sakuna and Pseudoregalia. While in-game, if I press the Steam button and then click on the store page or the media tab, it loads in the background, but I can't interact with the loaded page.

**Comment by steam3d** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/issues/613

**Comment by rasitayaz** [comment]
I misunderstood this issue, trying to find a fix right now.

**Comment by steam3d** [comment]
@rasitayaz check my solution, you simple need to stop rendering component.
 https://github.com/steam3d/MagicBlackDecky/blob/80e40aa0a5057a192c69212b3e2628325e03ad11/src/blackOverlay.tsx#L103
